### ISSUE TITLE
What podcasts do you listen to and why?

### ISSUE THREAD

**Issue by arthurvr** [skippednote/ama#6]

**Comment by skippednote** [comment]
>What podcasts do you listen to 
I've been avidly listening to [The Giant Robots Smashing into Other Giant Robots](http://giantrobots.fm/) for sometime now. 

>Why?
For staying upto date, perspective, and what not.
There is always a diverse category of speaker on Giant Robots. I've learnt about community building, functional programming, best practices, open source contributions, and a lot more.
